export const csvData = [
  {
    tableName: 'Attribute',
    data: [
      {
        identifier: 'deal_attribute_1',
        title: 'Priority',
        type: 'text',
      },
      {
        identifier: 'deal_attribute_2',
        title: 'Deal Value',
        type: 'number',
      },
      {
        identifier: 'deal_attribute_3',
        title: 'Close Date',
        type: 'date',
      },
      {
        identifier: 'deal_attribute_4',
        title: 'Source',
        type: 'text',
      },
      {
        identifier: 'deal_attribute_5',
        title: '',
        type: '',
      },
      {
        identifier: 'deal_attribute_6',
        title: '',
        type: '',
      },
      {
        identifier: 'deal_attribute_7',
        title: '',
        type: '',
      },
      {
        identifier: 'deal_attribute_8',
        title: '',
        type: '',
      },
      {
        identifier: 'deal_attribute_9',
        title: '',
        type: '',
      },
      {
        identifier: 'deal_attribute_10',
        title: '',
        type: '',
      },
      {
        identifier: 'deal_attribute_11',
        title: '',
        type: '',
      },
      {
        identifier: 'deal_attribute_12',
        title: '',
        type: '',
      },
      {
        identifier: 'deal_attribute_13',
        title: '',
        type: '',
      },
      {
        identifier: 'deal_attribute_14',
        title: '',
        type: '',
      },
      {
        identifier: 'deal_attribute_15',
        title: '',
        type: '',
      },
      {
        identifier: 'contact_attribute_1',
        title: 'Job Title',
        type: 'text',
      },
      {
        identifier: 'contact_attribute_2',
        title: 'Department',
        type: 'text',
      },
      {
        identifier: 'contact_attribute_3',
        title: 'Lead Score',
        type: 'number',
      },
      {
        identifier: 'contact_attribute_4',
        title: 'Last Contacted',
        type: 'date',
      },
      {
        identifier: 'contact_attribute_5',
        title: '',
        type: '',
      },
      {
        identifier: 'contact_attribute_6',
        title: '',
        type: '',
      },
      {
        identifier: 'contact_attribute_7',
        title: '',
        type: '',
      },
      {
        identifier: 'contact_attribute_8',
        title: '',
        type: '',
      },
      {
        identifier: 'contact_attribute_9',
        title: '',
        type: '',
      },
      {
        identifier: 'contact_attribute_10',
        title: '',
        type: '',
      },
      {
        identifier: 'contact_attribute_11',
        title: '',
        type: '',
      },
      {
        identifier: 'contact_attribute_12',
        title: '',
        type: '',
      },
      {
        identifier: 'contact_attribute_13',
        title: '',
        type: '',
      },
      {
        identifier: 'contact_attribute_14',
        title: '',
        type: '',
      },
      {
        identifier: 'contact_attribute_15',
        title: '',
        type: '',
      },
      {
        identifier: 'organization_attribute_1',
        title: 'Industry',
        type: 'text',
      },
      {
        identifier: 'organization_attribute_2',
        title: 'Employee Count',
        type: 'number',
      },
      {
        identifier: 'organization_attribute_3',
        title: 'Website',
        type: 'text',
      },
      {
        identifier: 'organization_attribute_4',
        title: 'Revenue',
        type: 'number',
      },
      {
        identifier: 'organization_attribute_5',
        title: '',
        type: '',
      },
      {
        identifier: 'organization_attribute_6',
        title: '',
        type: '',
      },
      {
        identifier: 'organization_attribute_7',
        title: '',
        type: '',
      },
      {
        identifier: 'organization_attribute_8',
        title: '',
        type: '',
      },
      {
        identifier: 'organization_attribute_9',
        title: '',
        type: '',
      },
      {
        identifier: 'organization_attribute_10',
        title: '',
        type: '',
      },
      {
        identifier: 'organization_attribute_11',
        title: '',
        type: '',
      },
      {
        identifier: 'organization_attribute_12',
        title: '',
        type: '',
      },
      {
        identifier: 'organization_attribute_13',
        title: '',
        type: '',
      },
      {
        identifier: 'organization_attribute_14',
        title: '',
        type: '',
      },
      {
        identifier: 'organization_attribute_15',
        title: '',
        type: '',
      },
    ],
  },
  {
    tableName: 'Contact',
    data: [
      {
        organization_name: 'Nexlify',
        role: 'CEO',
        name: 'Emma Carter',
        email: 'emma@nexlify.com',
        phone: '555-0201',
        contact_attribute_1: 'Chief Executive Officer',
        contact_attribute_2: 'Executive',
        contact_attribute_3: '95',
        contact_attribute_4: '2025-04-10',
        contact_attribute_5: '',
        contact_attribute_6: '',
        contact_attribute_7: '',
        contact_attribute_8: '',
        contact_attribute_9: '',
        contact_attribute_10: '',
        contact_attribute_11: '',
      },
      {
        organization_name: 'Nexlify',
        role: 'Manager',
        name: 'James Lee',
        email: 'james@nexlify.com',
        phone: '555-0202',
        contact_attribute_1: 'Operations Manager',
        contact_attribute_2: 'Operations',
        contact_attribute_3: '80',
        contact_attribute_4: '2025-04-08',
        contact_attribute_5: '',
        contact_attribute_6: '',
        contact_attribute_7: '',
        contact_attribute_8: '',
        contact_attribute_9: '',
        contact_attribute_10: '',
        contact_attribute_11: '',
      },
      {
        organization_name: 'GrowEasy',
        role: 'CTO',
        name: 'Sophia Patel',
        email: 'sophia@groweasy.com',
        phone: '555-0203',
        contact_attribute_1: 'Chief Technology Officer',
        contact_attribute_2: 'Technology',
        contact_attribute_3: '90',
        contact_attribute_4: '2025-04-12',
        contact_attribute_5: '',
        contact_attribute_6: '',
        contact_attribute_7: '',
        contact_attribute_8: '',
        contact_attribute_9: '',
        contact_attribute_10: '',
        contact_attribute_11: '',
      },
    ],
  },
  {
    tableName: 'Deal',
    data: [
      {
        address: '789 Pine St',
        nickname: 'CloudSync',
        board_name: 'Main Pipeline',
        stage_name: 'Negotiation',
        assignee_1: 'Alice Brown',
        assignee_2: '',
        assignee_3: '',
        assignee_4: 'Alice Brown',
        editor_1: '',
        editor_2: '',
        editor_3: 'Bob Wilson',
        editor_4: '',
        editor_5: '',
        editor_6: 'Emma Carter',
        editor_7: 'James Lee',
        editor_8: '',
        editor_9: '',
        editor_10: '',
        contact_1: 'Sophia Patel',
        contact_2: 'Lmao Contact',
        contact_3: '',
        contact_4: '',
        contact_5: '',
        contact_6: '',
        contact_7: '',
        contact_8: '',
        contact_9: '',
        contact_10: '',
        contact_11: '',
        contact_12: '',
        contact_13: '',
        contact_14: '',
        contact_15: '',
        deal_attribute_1: '',
        deal_attribute_2: '',
        deal_attribute_3: '',
        deal_attribute_4: '',
        deal_attribute_5: '',
        deal_attribute_6: '',
        deal_attribute_7: '',
        deal_attribute_8: '',
        deal_attribute_9: '',
        deal_attribute_10: '',
        deal_attribute_11: '',
        deal_attribute_12: '',
        deal_attribute_13: '',
        deal_attribute_14: '',
        deal_attribute_15: '',
      },
      {
        address: '101 Maple Dr',
        nickname: 'SmartGrow',
        board_name: 'Main Pipeline',
        stage_name: 'Proposal',
        assignee_1: 'Bob Wilson',
        assignee_2: '',
        assignee_3: '',
        assignee_4: 'Bob Wilson',
        editor_1: '',
        editor_2: '',
        editor_3: '',
        editor_4: '',
        editor_5: '',
        editor_6: 'Sophia Patel',
        editor_7: '',
        editor_8: '',
        editor_9: '',
        editor_10: '',
        contact_1: '',
        contact_2: '',
        contact_3: '',
        contact_4: '',
        contact_5: '',
        contact_6: '',
        contact_7: '',
        contact_8: '',
        contact_9: '',
        contact_10: '',
        contact_11: '',
        contact_12: '',
        contact_13: '',
        contact_14: '',
        contact_15: '',
        deal_attribute_1: '',
        deal_attribute_2: '',
        deal_attribute_3: '',
        deal_attribute_4: '',
        deal_attribute_5: 'Bad Deal Attribute',
        deal_attribute_6: '',
        deal_attribute_7: '',
        deal_attribute_8: '',
        deal_attribute_9: '',
        deal_attribute_10: '',
        deal_attribute_11: '',
        deal_attribute_12: '',
        deal_attribute_13: '',
        deal_attribute_14: '',
        deal_attribute_15: '',
      },
    ],
  },
  {
    tableName: 'Organization',
    data: [
      {
        name: 'Nexlify',
        organization_attribute_1: 'Technology',
        organization_attribute_2: '250',
        organization_attribute_3: 'www.nexlify.com',
        organization_attribute_4: '6000000',
        organization_attribute_5: '',
        organization_attribute_6: '',
        organization_attribute_7: 'BAD ORG ATTTR',
        organization_attribute_8: '',
        organization_attribute_9: '',
        organization_attribute_10: '',
        organization_attribute_11: '',
      },
      {
        name: 'GrowEasy',
        organization_attribute_1: 'Consulting',
        organization_attribute_2: '100',
        organization_attribute_3: 'www.groweasy.com',
        organization_attribute_4: '2000000',
        organization_attribute_5: '',
        organization_attribute_6: 'Bad Org attr',
        organization_attribute_7: '',
        organization_attribute_8: '',
        organization_attribute_9: '',
        organization_attribute_10: '',
        organization_attribute_11: '',
      },
    ],
  },
  {
    tableName: 'Stage',
    data: [
      {
        board_name: 'Main Pipeline',
        stage_name: 'Lead',
        order_index: '0',
      },
      {
        board_name: 'Main Pipeline',
        stage_name: 'Proposal',
        order_index: '1',
      },
      {
        board_name: 'Main Pipeline',
        stage_name: 'Negotiation',
        order_index: '2',
      },
      {
        board_name: 'Main Pipeline',
        stage_name: 'Closed',
        order_index: '3',
      },
    ],
  },
];
