import { PropsWithChildren } from "react";
import type { Metadata } from "next";

import { CsvDataProvider } from "@/lib/providers/CsvDataContext";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({ children }: Readonly<PropsWithChildren>) {
  return (
    <html lang="en" className="dark">
      <body>
        <CsvDataProvider>{children}</CsvDataProvider>
      </body>
    </html>
  );
}
